### ISSUE TITLE
having some difficulty increasing the right border edge to hide menu

### ISSUE THREAD

**Issue by Scotchman0** [EbenKouao/MMM-SmartTouch#1]
Hey! First just want to start off with: Thanks for making this plugin! It works super well and I've been enjoying it thus far. I have an IR Frame (USB) that handles input for me, and the baseline options are excellent! I have two questions and haven't been super lucky with cracking the style sheets so I figured I'd reach out:

1. I can't seem to increase the bounding edges for the frame of my display, so that it will hide the menu off screen (like I imagine it is supposed to do) so when I press the menu button it will summon. All I can get close to is the proper bounding edge of my display - 15x24" - and then it will go no further, no matter how much I adjust the 'right' bound. the result is it's always visible, just on the right edge over my weather plugin. Is there a quick fix you can suggest that might let me make it invisible while un-summoned, or, point me at the correct settings so I can adjust properly?

2. I'd LOVE to be able to patch new buttons into the js config file, but there doesn't seem to be a great way to include new icons to the list without committing my own version of the repository - is there any plans for a modified 'config' setup in the future that could be added for ease of access to newcomers like myself? 

config: {
button name: 'example',
icon: 'exclamation',
action: path/to/script/or/thing.sh,
},

Mostly this is about the hiding feature, but curious as to your thoughts on two - otherwise my plan is to just get better at coding in javascript. 

Thanks for your time!
~Will

**Comment by EbenKouao** [comment]
Hi Scotchman0, Thanks and I appreciate you trying out the project. 

1) The issue is the side menu isn't adjusting your screen size. Here's a quick fix by editing the CSS.

Open the MMM-SmartTouch/css/mmm-smarttouch.css 
Alter the CSS line 121: 
transform: translateX(600%); to say... transform: translateX(750%); 

What this will do is move the side menu of the screen (from the right). For now, you can experiment with the parameter values to best suit your monitor size. 
Likewise, you could alter line 133 to alter where you would like the side menu to be position once activated.

2) As of now, I won't look too much into adding additional features. But if you are interested, that would be great. If you plan to commit your own version to the repo with additional functionality, I'm happy to add to the master branch e.g. add the possibility of new buttons. 

Best,
Eben.

**Comment by Scotchman0** [comment]
Worked like a charm - now pops in perfectly the way it's intended. Thanks!

Really appreciate the quick reply! I'm working on a few adjustments re: additional buttons/opacity options etc - if I get them where I think they could be useful for others I'll submit a pull request for review. (Though, it might be awhile since JS isn't my go-to language of choice). 

Stay safe out there!
